reference: "data/reference/reference.fa"
reads_dir: "data/reads"
samples:
  - "sample"
  - "sample_CD4"
adapt1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
adapt2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"